# Site settings
title: Fokal
tag_text: Fokal
description: Fokal is a simple photography site with a focus on metadata.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

# Meta
locale:              en_US
timezone:            America/New_York
encoding:            utf-8

# social
twitter: fokalhq 

# SEO / Meta Tags
keywords: "fokal, stock photos, photography, photosharing, image search, images, free, creative commons"
