# Site settings
title: Sprioc
tag_text: Sprioc
description: Sprioc is a simple photography site with a focus on metadata.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed

# Meta
locale:              en_US
timezone:            America/New_York
encoding:            utf-8

# SEO / Meta Tags
keywords: "sprioc, stock photos, photography, photosharing, image search, images, free, creative commons"
